# Runtime configuration for Genie Space Enhancement System
command:
  - uvicorn
  - backend.main:app
  - --host
  - '0.0.0.0'
  - --port
  - '8000'

env:
  # Frontend static export location (Next.js output: 'export')
  - name: FRONTEND_EXPORT_DIR
    value: "frontend/out"

  # Python unbuffered output
  - name: PYTHONUNBUFFERED
    value: "1"

  # Note: DATABRICKS_HOST and DATABRICKS_TOKEN are NOT set here
  # Users must provide their own credentials in the Configure step
  # This ensures operations happen on behalf of the user with proper Genie permissions
