# Runtime configuration for Genie Space Enhancement System
command:
  - bash
  - start_app.sh

env:
  # Secrets will be interpolated by bundle deployment
  - name: DATABRICKS_TOKEN
    value: "{{secrets/genie-enhancement/service-token}}"

  - name: DATABRICKS_HTTP_PATH
    value: "{{secrets/genie-enhancement/sql-warehouse-http-path}}"

  # Python path - ensure imports work
  - name: PYTHONPATH
    value: "/app/python/source_code:$PYTHONPATH"

  # Frontend static export location (Next.js output: 'export')
  - name: FRONTEND_EXPORT_DIR
    value: "frontend/out"

  # Python unbuffered output
  - name: PYTHONUNBUFFERED
    value: "1"
