# Databricks Apps Configuration
# This file configures how the app runs in Databricks Apps environment

command: ['streamlit', 'run', 'app.py', '--server.port', '8000', '--server.address', '0.0.0.0']

env:
  # Streamlit settings
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_SERVER_HEADLESS'
    value: 'true'

  # Optional: Pre-configure these in Databricks Apps settings
  # - name: 'DATABRICKS_WAREHOUSE_ID'
  #   value: 'your-warehouse-id'
  # - name: 'GENIE_SPACE_ID'
  #   value: 'your-space-id'
  # - name: 'LLM_ENDPOINT'
  #   value: 'databricks-claude-sonnet-4'
