# Runtime configuration for Genie Lamp Agent
command:
  - uvicorn
  - backend.main:app
  - --host
  - '0.0.0.0'
  - --port
  - '8000'

env:
  # Databricks workspace connection (automatically injected by Databricks Apps)
  - name: DATABRICKS_HOST
    value: "{{workspace.host}}"

  - name: DATABRICKS_SERVER_HOSTNAME
    value: "{{workspace.server_hostname}}"

  # Databricks authentication token (from secrets scope)
  # Default: dev environment secrets
  # Override per target in databricks.yml (dev uses -dev suffix, prod uses -prod suffix)
  - name: DATABRICKS_TOKEN
    value: "{{secrets/genie-lamp/service-token-dev}}"

  # SQL Warehouse HTTP Path (from secrets scope)
  # Format: /sql/1.0/warehouses/<warehouse-id>
  # Override per target in databricks.yml
  - name: DATABRICKS_HTTP_PATH
    value: "{{secrets/genie-lamp/sql-warehouse-http-path-dev}}"

  # Frontend static export location (Next.js output: 'export')
  # Path is relative to /app/python/source_code (the working directory)
  - name: FRONTEND_EXPORT_DIR
    value: "frontend/out"

  # Python unbuffered output
  - name: PYTHONUNBUFFERED
    value: "1"
